kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-nima-examples
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helidon-nima-examples
  template:
    metadata:
      labels:
        app: helidon-nima-examples
        version: v1
    spec:
      volumes:
        - name: wallet
          configMap:
            name: wallet
      containers:
        - name: helidon-nima-examples
          image: ghcr.io/oracle-japan/java-on-azure-day-2023/helidon-nima-examples:1.0.0
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8080
          env:
            - name: oracle.ucp.jdbc.PoolDataSource.ds1.URL
              valueFrom:
                secretKeyRef:
                  name: datasource-secret
                  key: url
            - name: oracle.ucp.jdbc.PoolDataSource.ds1.user
              valueFrom:
                secretKeyRef:
                  name: datasource-secret
                  key: username
            - name: oracle.ucp.jdbc.PoolDataSource.ds1.password
              valueFrom:
                secretKeyRef:
                  name: datasource-secret
                  key: password
            - name: tracing.service
              valueFrom:
                secretKeyRef:
                  name: tracing-secret
                  key: tracing.service
            - name: tracing.protocol
              valueFrom:
                secretKeyRef:
                  name: tracing-secret
                  key: tracing.protocol
            - name: tracing.host
              valueFrom:
                secretKeyRef:
                  name: tracing-secret
                  key: tracing.host
            - name: tracing.port
              valueFrom:
                secretKeyRef:
                  name: tracing-secret
                  key: tracing.port
          readinessProbe:
            httpGet:
              path: /health/ready
              port: api
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: api
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - mountPath: /var/cache
              name: wallet
              readOnly: true
      imagePullSecrets:
        - name: ghcr-secret