apiVersion: v1
data:
  script.js: |-
    import http from 'k6/http';
    import { sleep } from 'k6';

    export default function () {
        http.get('http://app.azure.shukawam.me/item');
        sleep(1)
    }
kind: ConfigMap
metadata:
  name: k6-cm
  namespace: k6