apiVersion: batch/v1
kind: Job
metadata:
  name: k6-job
  namespace: k6
spec:
  completions: 1
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
        - image: grafana/k6
          name: k6-job
          args:
            - "run"
            - "--out"
            - "influxdb=http://influxdb.azure.shukawam.me/demo"
            - "--vus"
            - "5"
            - "--duration"
            - "5m"
            - "script.js"
          volumeMounts:
            - name: k6-script
              mountPath: /home/k6
      restartPolicy: Never
      volumes:
        - name: k6-script
          configMap:
            name: k6-cm