# Microprofile server properties
server:
  port: 8080
  host: 0.0.0.0

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics:
  rest-request:
    enabled: true

# Application properties. This is the default greeting
app:
  greeting: Hello

oracle:
  ucp:
    jdbc:
      PoolDataSource:
        ds1:
          URL: jdbc:oracle:thin:@atp_high?TNS_ADMIN=/home/shukawam/work/java-on-azure-day-2023/wallet
          connectionFactoryClassName: oracle.jdbc.replay.OracleDataSourceImpl
          user: ADMIN
          password: Wellcome#123
          connectionPoolName: JDBC_UCP_POOL
          initialPoolSize: 1
          minPoolSize: 1
          maxPoolSize: 1
          timeoutCheckInterval: 10
          inactiveConnectionTimeout: 10
          queryTimeout: 600
          fastConnectionFailoverEnabled: false
